language: python
python:
- 3.9
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run python -m pytest
- poetry run mypy *.py --ignore-missing-imports
- poetry run python -m pytest --cov-report xml --cov=. tests/
- bash <(curl -s https://codecov.io/bash)
